[package]
name = "calc-rs"
version = "1.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "calc"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[features]
default = ["ffi"]
ffi = []

[dependencies]
